# -*- coding: utf-8 -*-
{
    'name': "WooCommerce Connector",
    'summary': """Odoo WooCommerce Connector V14""",
    'description': 'Odoo WooCommerce Connector V14, WooCommerce, WooCommerce Odoo, WooCommerce Instance Connector, Odoo WooCommerce',
    'category': 'Sales',
    'version': '14.9.5.8.5',
    'author': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'website': 'https://www.cybrosys.com',
    'depends': [
        'base',
        'stock',
        'sale_management',
        'account',
        'sale_coupon',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/woocommerce.xml',
        'views/sub_menus.xml',
        'views/product_product.xml',
        'views/res_partner.xml',
        'views/sale_order.xml',
        'views/account_tax.xml',
        'views/brand.xml',
        'views/category.xml',
        'views/subtype.xml',
        'views/tlc.xml',
        'views/woo_attribute.xml',
        'wizard/product_wizard.xml',
    ],
    'images': ['static/description/banner.png'],
    "external_dependencies": {"python": ["WooCommerce", "django", "numpy"]},
    'installable': True,
    'application': True,
    'auto_install': False,
}
